project:
  type: website
  output-dir: docs

website:
  title: "2Hz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - A propos.qmd

format:
  html:
    theme: sandstone
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#94fff5"
    linkcolor: "#ef94ff"
    monofront: courier new
    css: styles.css
    toc: true
